name: Deploy UI to Azure

on:
  push:
    paths:
      - '**'
      - '!api.py'         # exclut les changements seulement côté API
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-ui -f Dockerfile.ui .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: mon-ui-app
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_UI }}
          images: my-ui
